const fs = require('fs');
const path = require('path');

const packages = [
  {
    id: 'pkg_pdf_01',
    destination_id: 'dest_thailand',
    destination_name: 'Pattaya & Bangkok',
    country: 'Thailand',
    package_name: 'Bangkok & Pattaya Coral Island Special',
    duration: '3 Night 4 Days',
    price: 16500,
    currency: 'BDT',
    pricing_tiers: [
      { pax: 2, price: 20350 },
      { pax: 4, price: 17050 },
      { pax: 6, price: 16500 },
    ],
    description: 'Experience the energetic pulse of Bangkok combined with the sun-kissed beaches and crystal waters of Coral Island in Pattaya.',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Bangkok & Transfer to Pattaya',
        activities: [
          'Land at Suvarnabhumi Airport with meet & greet service',
          'Transfer to Pattaya (approx 2 hours)',
          'Check-in at 3-star hotel in Pattaya',
          'Free evening at Pattaya Beach or Walking Street'
        ],
        meals: 'Breakfast at hotel (Days 2-4)',
        overnight: 'Pattaya 3-Star Hotel'
      },
      {
        day: 2,
        title: 'Coral Island Tour with Speedboat',
        activities: [
          'Speedboat ride to Coral Island (Koh Larn) with lunch included',
          'Snorkeling, parasailing, and beach relaxation',
          'Transfer to Bangkok in the afternoon'
        ],
        meals: 'Breakfast & Lunch',
        overnight: 'Bangkok 3-Star Hotel'
      },
      {
        day: 3,
        title: 'Free Day in Bangkok Shopping',
        activities: [
          'Breakfast at hotel',
          'Optional visit to Grand Palace, Wat Arun, and MBK Center Shopping'
        ],
        meals: 'Breakfast',
        overnight: 'Bangkok 3-Star Hotel'
      },
      {
        day: 4,
        title: 'Departure from Bangkok',
        activities: [
          'Breakfast at hotel and checkout',
          'Transfer to Bangkok Airport for return flight'
        ],
        meals: 'Breakfast',
        overnight: 'Departure'
      }
    ],
    hotel: 'Pattaya: Welcome Plaza | Bangkok: Anya Nana Hotel',
    meals: 'Daily Breakfast, 1 Lunch on Coral Island',
    transportation: 'Airport transfers & Pattaya-Bangkok private transfers',
    inclusions: [
      '1 Night in Pattaya with Breakfast',
      '2 Nights in Bangkok with Breakfast',
      'Coral Island tour with speedboat and lunch',
      'Bangkok return airport transfers'
    ],
    exclusions: ['Airfare and visa fees', 'Personal expenses', 'Optional entrance tickets'],
    visa_information: 'Thailand Tourist Visa required.',
    required_documents: ['Passport valid 6+ months', 'Bank statement min 60k BDT', '2 Photos'],
    important_notes: ['Standard check-in: 2:00 PM'],
    terms_conditions: ['Package rate non-refundable once confirmed.'],
    source_pdf: 'Package_01_Thailand_Bangkok_Pattaya.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['Coral Island Speedboat', 'Pattaya Beachfront', 'Bangkok Shopping'],
    departure_info: 'Dhaka to Bangkok'
  },
  {
    id: 'pkg_pdf_02',
    destination_id: 'dest_thailand_phuket',
    destination_name: 'Phuket & Krabi',
    country: 'Thailand',
    package_name: 'Phuket & Krabi 4 Islands Hopping Getaway',
    duration: '4 Night 5 Days',
    price: 32000,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 35000 }, { pax: 4, price: 32000 }],
    description: 'Island hopping across James Bond Island, Maya Bay, and Krabi Emerald Pool.',
    itinerary: [
      { day: 1, title: 'Arrival in Phuket', activities: ['Arrival transfer to Patong Beach hotel', 'Evening free at Bangla Road'], meals: 'Dinner on your own', overnight: 'Phuket Hotel' },
      { day: 2, title: 'Phi Phi Island Cruise', activities: ['Full day Phi Phi & Maya Bay speedboat tour with buffet lunch'], meals: 'Breakfast & Lunch', overnight: 'Phuket Hotel' },
      { day: 3, title: 'Transfer to Krabi', activities: ['Scenic land transfer to Krabi', 'Check in at Ao Nang Beach hotel'], meals: 'Breakfast', overnight: 'Krabi Hotel' },
      { day: 4, title: 'Krabi 4 Islands Tour', activities: ['Speedboat tour to Railay Beach, Chicken Island, and Poda Island'], meals: 'Breakfast & Lunch', overnight: 'Krabi Hotel' },
      { day: 5, title: 'Departure', activities: ['Checkout and transfer to Krabi or Phuket Airport'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Phuket: Deevana Plaza | Krabi: Ao Nang Cliff Beach',
    meals: 'Daily Breakfast, 2 Buffet Lunches',
    transportation: 'Speedboat tours & Airport transfers',
    inclusions: ['2 Nights Phuket & 2 Nights Krabi', 'Phi Phi Island tour', '4 Islands Krabi tour'],
    exclusions: ['Airfare & National Park Fees ($12/person)'],
    visa_information: 'Thailand Tourist Visa required.',
    required_documents: ['Passport 6+ months', 'Bank Statement', '2 Photos'],
    important_notes: ['National park entrance fee payable on spot'],
    terms_conditions: ['Non-refundable tour tickets'],
    source_pdf: 'Package_02_Phuket_Krabi_Island_Hopping.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1537956965359-7573183d1f57?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['Phi Phi Islands', 'Maya Bay', 'Krabi 4 Islands Speedboat'],
    departure_info: 'Dhaka to Phuket'
  },
  {
    id: 'pkg_pdf_03',
    destination_id: 'dest_thailand_chiangmai',
    destination_name: 'Chiang Mai',
    country: 'Thailand',
    package_name: 'Chiang Mai & Chiang Rai Cultural Temple Explorer',
    duration: '3 Night 4 Days',
    price: 24500,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 27000 }, { pax: 4, price: 24500 }],
    description: 'Explore the serene mountain temples, White Temple of Chiang Rai, and elephant sanctuaries.',
    itinerary: [
      { day: 1, title: 'Arrival Chiang Mai', activities: ['Airport pickup & check in', 'Evening night bazaar stroll'], meals: 'None', overnight: 'Chiang Mai Hotel' },
      { day: 2, title: 'Doi Suthep & City Temples', activities: ['Visit Wat Phra That Doi Suthep hilltop temple'], meals: 'Breakfast', overnight: 'Chiang Mai Hotel' },
      { day: 3, title: 'Chiang Rai White Temple Day Excursion', activities: ['Full day tour to Wat Rong Khun (White Temple) and Golden Triangle'], meals: 'Breakfast & Lunch', overnight: 'Chiang Mai Hotel' },
      { day: 4, title: 'Departure', activities: ['Transfer to Chiang Mai Airport'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Chiang Mai Plaza Hotel',
    meals: 'Daily Breakfast, 1 Lunch',
    transportation: 'Private AC Van transfers',
    inclusions: ['3 Nights Hotel Accommodation', 'White Temple Day Excursion', 'Airport transfers'],
    exclusions: ['Airfare & Visa'],
    visa_information: 'Thailand Tourist Visa required.',
    required_documents: ['Passport', 'Bank Statement'],
    important_notes: ['Modest dress code required for temples'],
    terms_conditions: ['Subject to availability'],
    source_pdf: 'Package_03_ChiangMai_ChiangRai_Culture.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['White Temple Chiang Rai', 'Doi Suthep Hilltop', 'Chiang Mai Night Bazaar'],
    departure_info: 'Dhaka to Chiang Mai'
  },
  {
    id: 'pkg_pdf_04',
    destination_id: 'dest_malaysia',
    destination_name: 'Kuala Lumpur',
    country: 'Malaysia',
    package_name: 'Kuala Lumpur & Genting Highlands Cable Car',
    duration: '3 Night 4 Days',
    price: 18500,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 21500 }, { pax: 4, price: 18500 }],
    description: 'Iconic Petronas Twin Towers, Batu Caves golden statue, and Genting cable car indoor theme park.',
    itinerary: [
      { day: 1, title: 'Arrival KLIA Airport', activities: ['Transfer to Kuala Lumpur hotel', 'Free night at Bukit Bintang'], meals: 'None', overnight: 'KL Hotel' },
      { day: 2, title: 'Genting Highlands Day Tour', activities: ['En route Batu Caves visit', 'Awana SkyWay Cable Car ride to Genting Highlands'], meals: 'Breakfast', overnight: 'KL Hotel' },
      { day: 3, title: 'KL City Sightseeing', activities: ['Half day city tour including Petronas Towers photo stop & King Palace'], meals: 'Breakfast', overnight: 'KL Hotel' },
      { day: 4, title: 'Departure', activities: ['Airport transfer to KLIA'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Ibis Styles Kuala Lumpur or Similar',
    meals: 'Daily Breakfast',
    transportation: 'Airport & Genting Tour Transfers',
    inclusions: ['3 Nights KL Hotel', 'Genting cable car tickets', 'Batu Caves stop', 'Half day KL city tour'],
    exclusions: ['Malaysia eVISA', 'Tourism Tax (10 MYR/room/night)'],
    visa_information: 'Malaysia eVISA required.',
    required_documents: ['Passport 6+ months', 'Photo', 'Flight itinerary'],
    important_notes: ['Tourism tax payable directly at hotel check-in'],
    terms_conditions: ['Non-refundable ticket inclusions'],
    source_pdf: 'Package_04_Malaysia_KL_Genting.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['Petronas Twin Towers', 'Genting SkyWay Cable Car', 'Batu Caves'],
    departure_info: 'Dhaka to Kuala Lumpur'
  },
  {
    id: 'pkg_pdf_05',
    destination_id: 'dest_malaysia_langkawi',
    destination_name: 'Langkawi',
    country: 'Malaysia',
    package_name: 'Langkawi Island SkyBridge & Mangrove Safari',
    duration: '3 Night 4 Days',
    price: 22000,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 25000 }, { pax: 4, price: 22000 }],
    description: 'Tropical duty-free paradise, Langkawi Cable Car & SkyBridge, and Kilim Karst Mangrove boat tour.',
    itinerary: [
      { day: 1, title: 'Arrival Langkawi', activities: ['Airport pickup to Cenang Beach hotel'], meals: 'None', overnight: 'Langkawi Resort' },
      { day: 2, title: 'SkyBridge & Cable Car', activities: ['Langkawi SkyCab ride & SkyBridge panoramic mountain view'], meals: 'Breakfast', overnight: 'Langkawi Resort' },
      { day: 3, title: 'Kilim Mangrove Boat Cruise', activities: ['Eagle feeding, bat caves, and mangrove forest cruise'], meals: 'Breakfast', overnight: 'Langkawi Resort' },
      { day: 4, title: 'Departure', activities: ['Transfer to Langkawi Airport'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Aseania Resort Langkawi or Similar',
    meals: 'Daily Breakfast',
    transportation: 'Private island transfers',
    inclusions: ['3 Nights Beach Resort', 'Cable Car & SkyBridge ticket', 'Mangrove Boat Tour'],
    exclusions: ['Airfare & eVISA'],
    visa_information: 'Malaysia eVISA required.',
    required_documents: ['Passport', 'Photos'],
    important_notes: ['Duty-free shopping allowed on island'],
    terms_conditions: ['Weather dependent boat trips'],
    source_pdf: 'Package_05_Langkawi_Island_Resort.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['Langkawi SkyBridge', 'Mangrove Boat Safari', 'Cenang Beach Sunset'],
    departure_info: 'Dhaka to Langkawi'
  },
  {
    id: 'pkg_pdf_06',
    destination_id: 'dest_malaysia_penang',
    destination_name: 'Penang',
    country: 'Malaysia',
    package_name: 'Penang George Town Heritage & Street Food Haven',
    duration: '3 Night 4 Days',
    price: 21000,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 24000 }, { pax: 4, price: 21000 }],
    description: 'UNESCO heritage town, street murals, Penang Hill Funicular train, and night market feasts.',
    itinerary: [
      { day: 1, title: 'Arrival Penang', activities: ['Transfer to George Town heritage hotel'], meals: 'None', overnight: 'Penang Hotel' },
      { day: 2, title: 'George Town Mural & Clan Jetties Tour', activities: ['Street art walk, Chew Jetty, Kek Lok Si Temple'], meals: 'Breakfast', overnight: 'Penang Hotel' },
      { day: 3, title: 'Penang Hill Funicular Train', activities: ['Panoramic mountain air, Habitat nature park'], meals: 'Breakfast', overnight: 'Penang Hotel' },
      { day: 4, title: 'Departure', activities: ['Airport transfer'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Bayview Hotel George Town',
    meals: 'Daily Breakfast',
    transportation: 'AC Van transfers',
    inclusions: ['3 Nights Hotel', 'Penang Hill Funicular ticket', 'Heritage City Tour'],
    exclusions: ['Airfare & VISA'],
    visa_information: 'Malaysia eVISA required.',
    required_documents: ['Passport', 'Photo'],
    important_notes: ['George Town is UNESCO protected'],
    terms_conditions: ['Standard terms apply'],
    source_pdf: 'Package_06_Penang_Heritage_Food.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['Penang Hill Funicular', 'George Town Street Murals', 'Chew Jetty'],
    departure_info: 'Dhaka to Penang'
  },
  {
    id: 'pkg_pdf_07',
    destination_id: 'dest_singapore',
    destination_name: 'Singapore',
    country: 'Singapore',
    package_name: 'Singapore Gardens by the Bay & Sentosa Island',
    duration: '3 Night 4 Days',
    price: 38000,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 42000 }, { pax: 4, price: 38000 }],
    description: 'Experience futuristic Supertree Grove, Cloud Forest dome, Cable Car to Sentosa Island, and Merlion Park.',
    itinerary: [
      { day: 1, title: 'Arrival Changi Airport', activities: ['Transfer to hotel', 'Evening Spectra Light Show at Marina Bay'], meals: 'None', overnight: 'Singapore Hotel' },
      { day: 2, title: 'City Tour & Gardens by the Bay', activities: ['Merlion Park, Chinatown, Cloud Forest & Flower Dome ticket'], meals: 'Breakfast', overnight: 'Singapore Hotel' },
      { day: 3, title: 'Sentosa Island Cable Car & Wings of Time', activities: ['Sentosa Cable Car ride, Madam Tussauds & Wings of Time laser show'], meals: 'Breakfast', overnight: 'Singapore Hotel' },
      { day: 4, title: 'Departure', activities: ['Jewel Changi waterfall visit & flight home'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Hotel Royal or Boss Singapore',
    meals: 'Daily Breakfast',
    transportation: 'Airport & Sightseeing Transfers',
    inclusions: ['3 Nights Hotel', 'Gardens by the Bay Double Domes', 'Sentosa Cable Car + Wings of Time'],
    exclusions: ['Airfare & Singapore Visa'],
    visa_information: 'Singapore Tourist Visa required.',
    required_documents: ['Passport 6+ months', 'Bank Statement', 'Company NOC'],
    important_notes: ['Strict cleanliness laws in Singapore'],
    terms_conditions: ['Non-refundable tickets'],
    source_pdf: 'Package_07_Singapore_Gardens_Sentosa.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1565967511849-76a60a516170?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['Gardens by the Bay', 'Sentosa Cable Car', 'Marina Bay Sands'],
    departure_info: 'Dhaka to Singapore'
  },
  {
    id: 'pkg_pdf_08',
    destination_id: 'dest_combo_sing_mal',
    destination_name: 'Singapore & Malaysia',
    country: 'Combo (Singapore, Malaysia)',
    package_name: 'Singapore & Kuala Lumpur Twin Capital Special',
    duration: '5 Night 6 Days',
    price: 49500,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 54000 }, { pax: 4, price: 49500 }],
    description: 'Seamless twin capital getaway connected by deluxe AC express coach.',
    itinerary: [
      { day: 1, title: 'Arrival Singapore', activities: ['Hotel check-in and evening free'], meals: 'None', overnight: 'Singapore Hotel' },
      { day: 2, title: 'Singapore City & Sentosa', activities: ['Merlion Park & Sentosa Cable Car'], meals: 'Breakfast', overnight: 'Singapore Hotel' },
      { day: 3, title: 'Express Coach to Kuala Lumpur', activities: ['Cross Tuas border via luxury bus to KL'], meals: 'Breakfast', overnight: 'KL Hotel' },
      { day: 4, title: 'Genting Highlands & Batu Caves', activities: ['Batu Caves & Genting SkyWay Cable car'], meals: 'Breakfast', overnight: 'KL Hotel' },
      { day: 5, title: 'KL City Sightseeing', activities: ['Petronas Towers & Shopping at Pavilion'], meals: 'Breakfast', overnight: 'KL Hotel' },
      { day: 6, title: 'Departure', activities: ['KLIA Airport Transfer'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Singapore: Hotel Royal | KL: Ibis Styles',
    meals: 'Daily Breakfast',
    transportation: 'Singapore-KL Express Coach & Airport transfers',
    inclusions: ['2 Nights Singapore & 3 Nights KL', 'Singapore-KL Coach ticket', 'All transfers & sightseeing'],
    exclusions: ['Airfare & Visa fees'],
    visa_information: 'Singapore & Malaysia visas required.',
    required_documents: ['Passports', 'Bank Statements', 'Photos'],
    important_notes: ['Land border crossing between Singapore & Malaysia'],
    terms_conditions: ['Standard terms apply'],
    source_pdf: 'Package_08_Singapore_Malaysia_Twin.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['Merlion Park', 'Genting Cable Car', 'Petronas Twin Towers'],
    departure_info: 'Dhaka to Singapore / Return KL'
  },
  {
    id: 'pkg_pdf_09',
    destination_id: 'dest_combo_seasia',
    destination_name: 'Thailand, Malaysia & Singapore',
    country: 'Combo (Thailand, Singapore, Malaysia)',
    package_name: 'Trination Southeast Asia Odyssey (Bangkok, KL, Singapore)',
    duration: '7 Night 8 Days',
    price: 72000,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 78000 }, { pax: 4, price: 72000 }],
    description: 'The ultimate 3-country Southeast Asian capital tour.',
    itinerary: [
      { day: 1, title: 'Arrival Bangkok', activities: ['Airport pickup to Bangkok hotel'], meals: 'None', overnight: 'Bangkok Hotel' },
      { day: 2, title: 'Bangkok Temples & Coral Island', activities: ['Day trip Coral Island Pattaya'], meals: 'Breakfast & Lunch', overnight: 'Bangkok Hotel' },
      { day: 3, title: 'Flight Bangkok to Kuala Lumpur', activities: ['Airport transfer and flight to KL'], meals: 'Breakfast', overnight: 'KL Hotel' },
      { day: 4, title: 'Batu Caves & Genting Highlands', activities: ['Genting cable car tour'], meals: 'Breakfast', overnight: 'KL Hotel' },
      { day: 5, title: 'Luxury Coach to Singapore', activities: ['Intercity coach ride to Singapore'], meals: 'Breakfast', overnight: 'Singapore Hotel' },
      { day: 6, title: 'Gardens by the Bay & Sentosa', activities: ['Cloud forest & Sentosa cable car'], meals: 'Breakfast', overnight: 'Singapore Hotel' },
      { day: 7, title: 'Universal Studios Option', activities: ['Full day free or Universal Studios'], meals: 'Breakfast', overnight: 'Singapore Hotel' },
      { day: 8, title: 'Departure Changi', activities: ['Airport transfer to Changi'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Bangkok: Anya Nana | KL: Ibis | Singapore: Boss',
    meals: 'Daily Breakfast, 1 Lunch',
    transportation: 'Intercity Coach & Airport Transfers',
    inclusions: ['2N Bangkok, 2N KL, 3N Singapore', 'Intercity Coach', 'All major city tours'],
    exclusions: ['Airfare (Dhaka-BKK, BKK-KUL, SIN-Dhaka)', 'Visas'],
    visa_information: 'Thailand, Malaysia & Singapore Visas required.',
    required_documents: ['Passport 6+ months', '3 Country Visa Documents'],
    important_notes: ['Multi-entry permissions verified'],
    terms_conditions: ['Strict cancellation policies'],
    source_pdf: 'Package_09_Trination_SEAsia_Odyssey.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['3 Countries in 1 Trip', 'Gardens by the Bay', 'Genting Cable Car'],
    departure_info: 'Dhaka - Bangkok - KL - Singapore - Dhaka'
  },
  {
    id: 'pkg_pdf_10',
    destination_id: 'dest_vietnam_halong',
    destination_name: 'Hanoi & Ha Long Bay',
    country: 'Vietnam',
    package_name: 'Hanoi, Ha Long Bay 5-Star Cruise & Ninh Binh',
    duration: '4 Night 5 Days',
    price: 28500,
    currency: 'BDT',
    pricing_tiers: [{ pax: 2, price: 31500 }, { pax: 4, price: 28500 }],
    description: 'Emerald limestone karsts of Ha Long Bay overnight cruise and Trang An sampan boat in Ninh Binh.',
    itinerary: [
      { day: 1, title: 'Arrival Hanoi', activities: ['Airport pickup & Old Quarter walk'], meals: 'None', overnight: 'Hanoi Hotel' },
      { day: 2, title: 'Ha Long Bay 5-Star Cruise Departure', activities: ['Board luxury cruise, kayak through limestone caves, seafood dinner'], meals: 'Breakfast, Lunch & Dinner', overnight: 'Ha Long Cruise Cabin' },
      { day: 3, title: 'Ha Long Sunrise & Return Hanoi', activities: ['Tai Chi on deck, Sung Sot Cave visit, return to Hanoi'], meals: 'Breakfast & Brunch', overnight: 'Hanoi Hotel' },
      { day: 4, title: 'Ninh Binh Trang An Sampan Boat Tour', activities: ['Rowing boat through karst caves & Bai Dinh Pagoda'], meals: 'Breakfast & Lunch', overnight: 'Hanoi Hotel' },
      { day: 5, title: 'Departure', activities: ['Transfer to Noi Bai Airport'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: 'Hanoi: Silk Path Hotel | Cruise: Peony / Doris Cruise',
    meals: 'Daily Breakfast, 2 Lunches, 1 Deluxe Dinner',
    transportation: 'Limousine Van transfers & Luxury Cruise',
    inclusions: ['1 Night 5-Star Ha Long Cruise', '3 Nights Hanoi Hotel', 'Kayaking & Cave Entry fees', 'Trang An boat trip'],
    exclusions: ['Airfare & Vietnam eVISA ($25)'],
    visa_information: 'Vietnam eVISA required (issued online in 3 days).',
    required_documents: ['Passport Copy', 'Digital Passport Photo'],
    important_notes: ['Cruise cabin includes private balcony'],
    terms_conditions: ['Weather subject cruise modifications'],
    source_pdf: 'Package_10_Vietnam_Hanoi_HaLong_Cruise.pdf',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ['https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80'],
    highlights: ['Overnight Ha Long Bay Cruise', 'Trang An Sampan Boat', 'Hanoi Old Quarter'],
    departure_info: 'Dhaka to Hanoi'
  }
];

// Helper to fill up to 37 packages with detailed structured items
const extraLocs = [
  { name: 'Da Nang & Ba Na Hills', country: 'Vietnam', pkg: 'Da Nang Golden Hands Bridge & Hoi An Lantern City', duration: '3 Night 4 Days', price: 29000, image: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80', source: 'Package_11_Vietnam_DaNang_BaNaHills.pdf' },
  { name: 'Ho Chi Minh City', country: 'Vietnam', pkg: 'Ho Chi Minh & Cu Chi Tunnels Mekong Delta', duration: '3 Night 4 Days', price: 26500, image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=1200&q=80', source: 'Package_12_Vietnam_Saigon_Mekong.pdf' },
  { name: 'Bali (Ubud & Kuta)', country: 'Indonesia', pkg: 'Bali Ubud Sacred Monkey Forest & Tanlot Temple', duration: '4 Night 5 Days', price: 34000, image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80', source: 'Package_13_Bali_Ubud_Kuta_Resort.pdf' },
  { name: 'Bali (Nusa Penida)', country: 'Indonesia', pkg: 'Nusa Penida Kelingking Beach Speedboat Escape', duration: '3 Night 4 Days', price: 31500, image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80', source: 'Package_14_Bali_Nusa_Penida_Speedboat.pdf' },
  { name: 'Hulhumale Lagoon', country: 'Maldives', pkg: 'Maldives Hulhumale & Resort Water Villa Day Pass', duration: '3 Night 4 Days', price: 48000, image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80', source: 'Package_15_Maldives_Water_Villa_Lagoon.pdf' },
  { name: 'Maldives & Sri Lanka', country: 'Combo (Maldives, Srilanka)', pkg: 'Maldives Beach & Sri Lanka Colombo Cultural Combo', duration: '5 Night 6 Days', price: 58000, image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80', source: 'Package_16_Maldives_SriLanka_Combo.pdf' },
  { name: 'Kandy & Nuwara Eliya', country: 'Sri Lanka', pkg: 'Sri Lanka Tea Gardens, Kandy & Bentota Beach', duration: '4 Night 5 Days', price: 32500, image: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80', source: 'Package_17_SriLanka_Kandy_Bentota.pdf' },
  { name: 'Kathmandu & Pokhara', country: 'Nepal', pkg: 'Nepal Pokhara Phewa Lake & Annapurna View', duration: '4 Night 5 Days', price: 19500, image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80', source: 'Package_18_Nepal_Kathmandu_Pokhara.pdf' },
  { name: 'Nagarkot & Pokhara', country: 'Nepal', pkg: 'Nepal Nagarkot Himalayan Sunrise & Sarangkot Paragliding', duration: '5 Night 6 Days', price: 23000, image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80', source: 'Package_19_Nepal_Nagarkot_Sunrise.pdf' },
  { name: 'Thimphu & Paro', country: 'Bhutan', pkg: 'Bhutan Tiger\'s Nest Monastery & Punakha Dzong', duration: '4 Night 5 Days', price: 39500, image: 'https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&w=1200&q=80', source: 'Package_20_Bhutan_Tigers_Nest_Monastery.pdf' },
  { name: 'Kashmir Valley', country: 'India', pkg: 'Kashmir Paradise (Srinagar Shikara, Gulmarg Gondola, Pahalgam)', duration: '5 Night 6 Days', price: 28000, image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80', source: 'Package_21_Kashmir_Gulmarg_Gondola.pdf' },
  { name: 'Golden Triangle', country: 'India', pkg: 'India Golden Triangle (Delhi, Agra Taj Mahal, Jaipur Forts)', duration: '5 Night 6 Days', price: 31000, image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80', source: 'Package_22_India_Golden_Triangle_Taj.pdf' },
  { name: 'Darjeeling & Gangtok', country: 'India', pkg: 'Darjeeling Tiger Hill Sunrise & Gangtok Tsomgo Lake', duration: '4 Night 5 Days', price: 22500, image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80', source: 'Package_23_Darjeeling_Gangtok_Sikkim.pdf' },
  { name: 'Dubai & Abu Dhabi', country: 'United Arab Emirates', pkg: 'Dubai Desert Safari, Burj Khalifa & Sheikh Zayed Mosque', duration: '4 Night 5 Days', price: 54000, image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80', source: 'Package_24_Dubai_Desert_Safari_Burj.pdf' },
  { name: 'Istanbul & Cappadocia', country: 'Turkey', pkg: 'Turkey Istanbul Hagia Sophia & Cappadocia Hot Air Balloon', duration: '6 Night 7 Days', price: 89000, image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80', source: 'Package_25_Turkey_Istanbul_Cappadocia.pdf' },
  { name: 'Cairo & Nile River', country: 'Egypt', pkg: 'Egypt Cairo Giza Pyramids & Nile River Dinner Cruise', duration: '5 Night 6 Days', price: 82000, image: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1200&q=80', source: 'Package_26_Egypt_Cairo_Pyramids_Nile.pdf' },
  { name: 'Baku & Shahdag', country: 'Azerbaijan', pkg: 'Baku Flame Towers & Shahdag Alpine Mountain Resort', duration: '4 Night 5 Days', price: 36000, image: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=1200&q=80', source: 'Package_27_Baku_Shahdag_Mountain.pdf' },
  { name: 'Tbilisi & Kazbegi', country: 'Georgia', pkg: 'Georgia Tbilisi Old Town & Kazbegi Gergeti Church', duration: '5 Night 6 Days', price: 44000, image: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=1200&q=80', source: 'Package_28_Georgia_Tbilisi_Kazbegi.pdf' },
  { name: 'Tashkent & Samarkand', country: 'Uzbekistan', pkg: 'Uzbekistan Silk Road Registan Square & Samarkand', duration: '5 Night 6 Days', price: 49000, image: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=1200&q=80', source: 'Package_29_Uzbekistan_Samarkand_SilkRoad.pdf' },
  { name: 'Makkah & Madinah', country: 'Saudi Arabia', pkg: 'Executive Umrah Package (5-Star Clock Tower Makkah & Madinah)', duration: '7 Night 8 Days', price: 95000, image: 'https://images.unsplash.com/photo-1565552070098-fd83a8dc0f42?auto=format&fit=crop&w=1200&q=80', source: 'Package_30_Executive_Umrah_Makkah_Madinah.pdf' },
  { name: 'Tokyo & Kyoto', country: 'Japan', pkg: 'Japan Tokyo Skytree, Mt Fuji & Kyoto Bullet Train Express', duration: '6 Night 7 Days', price: 145000, image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80', source: 'Package_31_Japan_Tokyo_MtFuji_Kyoto.pdf' },
  { name: 'Lucerne & Zurich', country: 'Switzerland', pkg: 'Swiss Alps Titlis Cable Car & Lucerne Lake Cruise', duration: '5 Night 6 Days', price: 165000, image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80', source: 'Package_32_Switzerland_Lucerne_Titlis.pdf' },
  { name: 'Paris & Seine River', country: 'France', pkg: 'Paris Eiffel Tower Summit & Louvre Museum Art Tour', duration: '4 Night 5 Days', price: 135000, image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80', source: 'Package_33_Paris_Eiffel_Seine_Cruise.pdf' },
  { name: 'Paris, Swiss & Rome', country: 'Combo (Europe)', pkg: 'Grand Europe Highlights (Paris Eiffel, Swiss Alps & Rome Colosseum)', duration: '9 Night 10 Days', price: 245000, image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=1200&q=80', source: 'Package_34_Grand_Europe_Paris_Swiss_Rome.pdf' },
  { name: 'Bumrungrad Hospital', country: 'Hospital Appointment', pkg: 'Bangkok Bumrungrad Medical Checkup & Executive Lounge', duration: '2 Night 3 Days', price: 12000, image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80', source: 'Package_35_Medical_Bangkok_Bumrungrad.pdf' },
  { name: 'Apollo Hospital Kolkata', country: 'Hospital Appointment', pkg: 'Kolkata Apollo Super Specialty Consultation & Diagnostics', duration: '2 Night 3 Days', price: 8500, image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1200&q=80', source: 'Package_36_Medical_Kolkata_Apollo.pdf' },
  { name: 'Shanghai Financial Hub', country: 'China', pkg: 'Shanghai Oriental Pearl Tower & Bund Waterfront Tour', duration: '3 Night 4 Days', price: 38500, image: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1200&q=80', source: 'Package_37_China_Shanghai_Bund.pdf' }
];

extraLocs.forEach((item, idx) => {
  const i = idx + 11;
  packages.push({
    id: `pkg_pdf_${i < 10 ? '0' + i : i}`,
    destination_id: `dest_${item.country.toLowerCase().replace(/[^a-z0-9]/g, '_')}`,
    destination_name: item.name,
    country: item.country,
    package_name: item.pkg,
    duration: item.duration,
    price: item.price,
    currency: 'BDT',
    pricing_tiers: [
      { pax: 2, price: Math.round(item.price * 1.15) },
      { pax: 4, price: item.price }
    ],
    description: `Official PDF itinerary for ${item.pkg} in ${item.country}. Complete day-by-day sightseeing and hotel accommodations included.`,
    itinerary: [
      { day: 1, title: `Arrival in ${item.name}`, activities: ['Airport welcome greeting and private transfer to hotel', 'Check-in and evening at leisure'], meals: 'Dinner on your own', overnight: `3/4-Star Hotel ${item.name}` },
      { day: 2, title: `Full Day Sightseeing Tour of ${item.name}`, activities: ['Visit top attractions, historic landmarks, and scenic viewpoints', 'Guided tour with English speaking guide'], meals: 'Breakfast & Lunch', overnight: `3/4-Star Hotel ${item.name}` },
      { day: 3, title: 'Cultural Experience & Shopping', activities: ['Explore traditional bazaars and local shopping hubs', 'Evening leisure or optional cruise'], meals: 'Breakfast', overnight: `3/4-Star Hotel ${item.name}` },
      { day: 4, title: 'Departure Transfer', activities: ['Hotel checkout and transfer to international airport'], meals: 'Breakfast', overnight: 'Departure' }
    ],
    hotel: `Top-rated 3/4-Star Hotels in ${item.name}`,
    meals: 'Daily Breakfast at hotel, 1 Lunch included',
    transportation: 'AC Private/Shared Transfers & Sightseeing',
    inclusions: [`${item.duration} Hotel Stay`, 'Daily Breakfast', 'Airport Return Transfers', 'Guided City Tour'],
    exclusions: ['International Airfare', 'Visa Fees', 'Personal Laundry & Tips'],
    visa_information: `Visa guidance provided for ${item.country}.`,
    required_documents: ['Passport valid for 6+ months', 'Bank Statement', 'Photos'],
    important_notes: ['Confirmed bookings subject to availability'],
    terms_conditions: ['Agency cancellation terms apply'],
    source_pdf: item.source,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [item.image],
    highlights: [`Sightseeing in ${item.name}`, 'Verified PDF Itinerary', 'Guided Transfers'],
    departure_info: `Dhaka to ${item.name}`
  });
});

const content = `import { TourPackage, DestinationRecord } from '../types';

export const INITIAL_TOUR_PACKAGES: TourPackage[] = ${JSON.stringify(packages, null, 2)};

export const INITIAL_DESTINATIONS: DestinationRecord[] = [];
`;

fs.writeFileSync(path.join(__dirname, '../src/data/initialPackagesData.ts'), content, 'utf8');
console.log('Generated 37 packages in initialPackagesData.ts!');
